name: flat

grid_shape: [5, 5, 5, 5, 5, 5]
bd_min: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
bd_max: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0]

genotype_setup:

  structure_args:

    structure_size: 20
    max_chambers: 5
    max_connections: 20
    expansion_threshold: 0.5
    expansion_perimeter: 1

    mutation_chamber_p: 0.5
    mutation_add_chamber_p: 0.2
    mutation_connection_p: 0.2
    cross_over_p : 0.2
  
  gameplay_args:

      window_size: 3
      num_features: 3
      layer_sizes: [16,16]
      iso_sigma:  0.005
      line_sigma: 0.05
      input_middle: True

scoring_fn: 'combined'
scoring_fn_args:  

  min_size: 15
  min_distance: 8
  gameplay_range: [0.1, 0.3]

  d_weight: 1
  g_weight: 1
  cc_weight: 1
  bonus_weight: 0.2